INSERT INTO tabela_de_vendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO) 
VALUES 
('00233', 'Joao Geraldo da Fonseca', 0.10);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
 ('00235','Márcio Almeida Silva',0.08);
 
 INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00236','Cláudia Morais',0.08);

select * from tabela_de_vendedores